Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,1 +1,29 @@
+name: example-actions-docker
+on:
+  push:
+    branches: ["main"]
 
+jobs:
+  build-push:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ inputs.branch }}
+
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_KEY}}
+
+      - name: Build and push Docker image
+        run: |
+          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.service }}:${{ github.sha }}"
+          echo "Building image: $IMAGE_NAME"
+          docker build ./${{ inputs.service }} -t $IMAGE_NAME || { echo "Failed to build image"; exit 1; }
+
+          echo "Pushing image: $IMAGE_NAME"
+          docker push $IMAGE_NAME || { echo "Failed to push image"; exit 1; }
